name: Go Test

on:
  pull_request:
    branches:
      - main
      - release/*
  push:
    branches:
      - main
      - release/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache-dependency-path: "**/*.sum"
      - name: Install dependencies
        run: go mod download
      - name: Test with Go
        run: go test ./... -v
